CREATE TABLE SITE_BINS(
SITE    TEXT   NOT NULL,
YEAR    INTEGER NOT NULL,
MONTH   INTEGER   NOT NULL,
DAY     INTEGER      NOT NULL,
HOUR INTEGER NOT NULL,
MINUTE INTEGER NOT NULL,
WEEKDAY INTEGER NOT NULL,
FREQ INTEGER NOT NULL,

CONSTRAINT PK_SITE_DATA PRIMARY KEY (SITE, YEAR, MONTH, DAY, HOUR, MINUTE)
);


CREATE TABLE SC_WAIT(
SITE    TEXT   NOT NULL,
YEAR    INTEGER NOT NULL,
MONTH   INTEGER   NOT NULL,
DAY     INTEGER      NOT NULL,
HOUR INTEGER NOT NULL,
MINUTE INTEGER NOT NULL,
WEEKDAY INTEGER NOT NULL,
FREQ INTEGER NOT NULL,

CONSTRAINT PK_SITE_DATA PRIMARY KEY (SITE, YEAR, MONTH, DAY, HOUR, MINUTE)
);
