CREATE TABLE SITE_DATA(
ENTRY_KEY INTEGER NOT NULL,
SITE    TEXT   NOT NULL,
YEAR    INTEGER NOT NULL,
MONTH   INTEGER   NOT NULL,
DAY     INTEGER      NOT NULL,
HOUR INTEGER NOT NULL,
MINUTE INTEGER NOT NULL,
WEEKDAY INTEGER NOT NULL,

CONSTRAINT PK_SITE_DATA PRIMARY KEY (ENTRY_KEY)
);
